### PR TITLE
#17 Add support for multiple require statements

### PR DESCRIPTION
**Pull request by michaelw85**
Added support for:

> var moduleA = require('moduleA');

### CODE REVIEW

**Comment by anacierdem** [comment]
When I try to goto definition on moduleA or foo;
`define(function(require) {
    var moduleA = require('moduleA');
    moduleA.foo()
});`

Get the following console error without any definition listed.

`Cannot read property '0' of undefined: TypeError: Cannot read property '0' of undefined
    at result.forEach (c:\Users\Ali Naci Erdem\Documents\SourceCode\vscode-requirejs\extension.js:42:70)
    at Array.forEach (native)
    at ReferenceProvider.getModulesWithPathFromRequireOrDefine (c:\Users\Ali Naci Erdem\Documents\SourceCode\vscode-requirejs\extension.js:42:20)
    at ReferenceProvider.provideDefinition (c:\Users\Ali Naci Erdem\Documents\SourceCode\vscode-requirejs\extension.js:218:35)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:351152
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57373
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:46346)
    at Object.d [as asWinJsPromise] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57336)
    at e.provideDefinition (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:351106)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:361457`

**Comment by michaelw85** [comment]
Ok, adding your example as a test file and will fix the issue.
I really hope no one actually uses one liners like that. It just look horrible.

**Comment by michaelw85** [comment]
Ok fixed it. Manually tested all test scenario's everything seems to work as expected for me.

Side note:
When I test your example for the `moduleA.foo()` part it will go to `moduleA` not the `foo` method. I think this could be improved but I think we should treat it as a separate task. I tested the current code in master and the scenario that you provided is not supported at all.

**Comment by anacierdem** [comment]
You are right I was testing with the old code. Also single line was not intentional :)
Your solution seem to work fine.

**Comment by anacierdem** [comment]
Ok, the problem is with multi line dependency lists. I have added two new test files for this and multi require/define statements.

**Comment by michaelw85** [comment]
Is this a new issue introduced with my changes? If so, let me fix it. If not lets treat it as a new feature request merge these changes then fix it.

**Comment by anacierdem** [comment]
Yes it is caused by the changes.

**Comment by michaelw85** [comment]
I was just thinking about it. Its probably because I simplified the regex to get the define statement. Setting it to multi line should fix it I think. I will give it a try tonight.

**Comment by michaelw85** [comment]
Ok your new test file was a bit more challenging than anticipated but I got everything working now!
Added more tests.

Only scenario that is not supported right now is multiple require/define statements with multi line module definition. Not sure if we want to support this but I would like to treat this as a separate feature if we need to support it.

**Comment by anacierdem** [comment]
Yes, writing goto definition is a challenge indeed :) Your changes seems nice to me.

**Comment by anacierdem** [comment]
See #26, #27, and #28

**Comment by anacierdem** [comment]
Reverted changes. 

`fullText.match(/(require|define)/g)` matches incorrect things in the file such as "undefined".

There are also other issues. Please review and send a new pull request that will not cause such issues with general js code.

**Pull request merged**
